### ISSUE TITLE
调度问题咨询

### ISSUE THREAD

**Issue by ChunelFeng** [symphony09/ograph#1]
个人感觉，这篇文章中，提到的 M和P 的思路：https://learnku.com/articles/87374

像是在 M 和 本地队列的 m:n 的数量中，构建了一个中间桥梁，
屏蔽了 m（理论很小的cpu线程数）和 n（实际上可能非常大的本地队列数）之间 不对等的关系。

可能还有一个好处，在队列为空的情况下，新来的 task可以不进入 queue，而直接进入P，让M执行，
从而减少一次 入queue和出queue的耗时

想请教几个问题：
1. 图【场景8】中，将g8 放到 p2队列中的操作，是谁来负责的？有中央调度器么?
2. 关于work-steal，是否有思路，如何更加快速的定位到，哪个 queue 中有任务。以便减少steal 的次数，提高命中率

非常期待和您取得联系，以请教和学习更多内容。
我的微信是 ChunelFeng

**Comment by symphony09** [comment]
对于第一个问题，应该是由图中的M2线程自己负责的。可以参考下图：

M线程在 g0 栈上执行 schedule 函数时根据调度策略（调用 findRunnable 函数）选择一个可运行的 g，
其中就涉及work-steal（调用 stealWork 函数）。

schedule ，findRunnable ，stealWork 这几个函数都在 go 源码 runtime/proc.go 中。

![image](https://github.com/user-attachments/assets/91ce58f8-c4ce-4d7a-b09e-4eb3c34dee54)

**Comment by symphony09** [comment]
对于第二个问题，在 go 中是通过遍历 P 来获取可偷窃任务的。

对于一个两核的机器，一般 p 的数量也就是两个，那么不管 M 线程有多少个，最多也只需要尝试两次。

此外，窃取算法使用了一个枚举器 stealOrder 来决定遍历 P 的顺序，这有助于减少争用和提供更好的负载均衡。也相当于间接的提高了命中率。
